language: node_js
notifications:
  slack:
    rooms:
      - reactator:4NOjOc5k5ykc737FbQW0zQVx#general
      - reactator:4NOjOc5k5ykc737FbQW0zQVx#ci
node_js:
  - "6.3.1"
before_install:
  - npm -v
  - node -v
  - npm install -g babel-cli
install:
  - npm install
script:
  - npm run clean
  - npm run lint
  - npm run test
  - npm run build
  - npm run doc